apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventorySelectorTemplate
metadata:
  name: location-central-selector
  namespace: fleet-default
spec:
  template:
    spec:
      selector:
        matchLabels:
          tz: "central"
