apiVersion: 1.1
image:
  imageType: iso
  arch: x86_64
  baseImage: SL-Micro.x86_64-6.0-Default-SelfInstall-GM2.install.iso
  outputImageName: elemental-image.iso
operatingSystem:
  packages:
    sccRegistrationCode: YOUR_SCC_REGISTRATION_CODE
  isoConfiguration:
    installDevice: /dev/vda
  users:
    - username: root
      encryptedPassword: $6$6.BTfqV5fsAo.vFE$sm9k5K7yobOTc9MUaoapd6pQQfpIp5buZgJKbLG2Ddv3/Tdo73ylvrpTCEkBWJ14n5fmbQLrIcTTQ31NNQjFU0
